### ISSUE TITLE
kubelet patcher script binary patcher thingy

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/sig-windows-tools#124]
Was talking to @perithompson today, and we're going to build 
a PS1 script that hot patches kubelet.exe.. for iterative development on various
things wed like to try in the kubelet

part 1
- define an optional wget location for where to get kubelet.exe from
- if something new is in the bucket, pull it down

part 2 
- define a directory for kube binaries
- have a poll step in the `while true`, for the PS1 script to continually check for new files (kubelet.exe, others?)
- if the directory contents change
- restart kubelet.exe
- run a quick sanity check that services are still working

Feels like this is particularly valuable bc you cannot build the kubelet.exe on the actual windows nodes

**Comment by perithompson** [comment]
```yaml
#rebuild k/k
#patcher.exe
#e2etests

windows:
  hosts:
  - win-node1
  - win-node2
  - win-node3
  components:
    - kubelet.exe:
        src: go/src/k8s.io/kubelet.exe
        dst: c:/k/kubelet.exe
        prepatch: stop-service kubelet
        postpatch: start-service kubelet
        depends_on: 
        - containerd
    - containerd.exe:
        src: ./containerd.exe
        dst: c:/program files/containerd/containerd.exe
        prepatch: stop-service containerd --force
        postpatch: start-service containerd
    - ctr.exe:
        src: ./containerd.exe
        dst: c:/program files/containerd/containerd.exe
        prepatch: stop-service containerd --force
        postpatch: start-service containerd
    - hcsshim.exe:
        src: ./containerd.exe
        dst: c:/program files/containerd/hcsshim.exe
        prepatch: stop-service containerd --force
        postpatch: start-service containerd
```
