### ISSUE TITLE
kube-flannel for linux fails to (re)start after rbac for kube-flannel for windows is applied

### ISSUE THREAD

**Issue by Mik4sa** [kubernetes-sigs/sig-windows-tools#277]
**Describe the bug**
Following [this guide](https://github.com/kubernetes-sigs/sig-windows-tools/blob/master/guides/guide-for-adding-windows-node.md) for Kubernetes 1.26.0 the kube-flannel pod for linux is failing to start after a restart of the control plane (where the pod was running on). I no longer have the actual error message but the problem was that the service account used didn't have enough permissions.

I already analyzed that. The reason is the rbac file we need to apply at last:
> 5. Apply kube-flannel-rbac.yml from sig-windows-tools/kubeadm/flannel
> Next you will need to apply the configuration that allows flannel to spawn pods and keep them running:
> 
> ```bash
> kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/sig-windows-tools/master/hostprocess/flannel/flanneld/kube-flannel-rbac.yml
> ```

This one overwrites the `ClusterRole` and `ClusterRoleBinding` created by:
> 3. Apply the Flannel manifest and validate
> 
> Let's apply the Flannel configuration:
> 
> ```bash
> kubectl apply -f kube-flannel.yml
> ```
___
To overcome this I used a customized rbac file. This one works around the described issue:
``` yaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flannel
  namespace: kube-system
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: flannel-windows
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flannel
subjects:
  - kind: ServiceAccount
    name: flannel
    namespace: kube-system
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: kube-flannel-cfg
  namespace: kube-system
  labels:
    tier: node
    app: flannel
data:
  cni-conf.json: |
    {
      "name": "cbr0",
      "plugins": [
        {
          "type": "flannel",
          "delegate": {
            "hairpinMode": true,
            "isDefaultGateway": true
          }
        },
        {
          "type": "portmap",
          "capabilities": {
            "portMappings": true
          }
        }
      ]
    }
  net-conf.json: |
    {
      "Network": "10.244.0.0/16",
      "Backend": {
        "Type": "vxlan"
      }
    }

```

The `ClusterRole` is completly removed and the `ClusterRoleBinding` is renamed from `flannel` to `flannel-windows`. So we use the `ClusterRole` from flannel directly (defined in https://raw.githubusercontent.com/kubernetes-sigs/sig-windows-tools/master/hostprocess/flannel/flanneld/kube-flannel-rbac.yml). This works because it uses the same rules with some extra ones.

**But note**, I don't feel like this is the actual solution we should use. IMO we should move the kube-flannel pods for windows from `kube-system` to `kube-flannel` aswell and may or may not reuse the `ServiceAccount` defined by the original flannel. So we get rid of a custom `ServiceAccount`, `ClusterRole` and `ClusterRoleBinding`.

**To Reproduce**
Just follow the guide to add a (new) windows node: https://github.com/kubernetes-sigs/sig-windows-tools/blob/master/guides/guide-for-adding-windows-node.md and restart the node where the kube-flannel pod for linux is running (or simply restart that pod, though I didn't tried that way)

**Expected behavior**
After restarting any node (or the kube-flannel pods directly) the cluster (networking) should still work as expected.

**Kubernetes (please complete the following information):**
 - Windows Server version: Windows Server 2022 (21H2, Build 20348.1366)
 - Kubernetes Version: 1.26.0
 - CNI: flannel
