### ISSUE TITLE
Windows Node on Kubernetes v1.26.0 can't use NodePort to access service

### ISSUE THREAD

**Issue by dnsdhcp** [kubernetes-sigs/sig-windows-tools#279]
**Kubernetes (please complete the following information):**
 - Kubernetes Version: v1.26.0
 - CNI: calico v3.24.5
 -  Control Plane x 1 ( RHEL 8.7 )
 -  Windows Worker Node x 2  ( Windows Server version: 1809 OS Build 17763.3770 )

**Describe the bug**

I was creating pod and service using the following YAML.

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: "myiis"
  namespace: default
  labels:
    app: "myiis"
spec:
  containers:
  - name: myiis
    image: "mcr.microsoft.com/windows/servercore/iis:windowsservercore-ltsc2019"
    ports:
    - containerPort: 80
      name: http
  nodeSelector:
    kubernetes.io/os: windows
  restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: myiis
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: myiis
  type: NodePort
```
I can only access `myiis` service on the node that running the pod.

```
[user@control ~]$  kubectl get node
NAME         STATUS     ROLES           AGE    VERSION
control      Ready      control-plane   7d3h   v1.26.0
winnode2     Ready      <none>          121m   v1.26.0
winsrv2019   Ready      <none>          7d3h   v1.26.0
```

```
[user@control ~]$ kubectl  get pods -o wide
NAME    READY   STATUS    RESTARTS   AGE   IP               NODE       NOMINATED NODE   READINESS GATES
myiis   1/1     Running   0          21s   192.168.74.131   winnode2   <none>           <none>
```

```
[user@control ~]$  kubectl get svc
NAME         TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)        AGE
kubernetes   ClusterIP   10.96.0.1       <none>        443/TCP        7d3h
myiis        NodePort    10.105.1.231    <none>        80:31884/TCP   113s
```

I can access to the service using the specific node IP address and it's NodePort.

```
[user@control ~]$ curl http://winnode2:31884 -I
HTTP/1.1 200 OK
```
But I can't access to the other nodes either Windows node nor Linux Node with the NodePort.

```
[user@control ~]$ curl http://winsrv2019:31884 -I
curl: (7) Failed to connect to winsrv2019 port 31884: Connection timed out
```

**Expected behavior**

The service should be accessible through every Node in the Kubernetes cluster.
