### ISSUE TITLE
Document working steps to add a Windows node

### ISSUE THREAD

**Issue by riverar** [kubernetes-sigs/sig-windows-tools#293]
There's widespread confusion and seemingly no end to outdated documentation relating to the addition of a Windows node. I believe, as part of the SIG-Windows charter, Windows node documentation (with any supported/working CNI) should live here and be maintained.

Examples of non-working solutions I've stumbled on thus far:

## Canonical MicroK8s
Relies on non-working Calico configuration (see below).
Docs: https://microk8s.io/docs/add-a-windows-worker-node-to-microk8s

## Calico
Ships a non-working kubelet configuration
Tracking issue: https://github.com/projectcalico/calico/issues/7552

## SIG-Windows
Contains a CNI/containerd warning, unknown status. Tracking PR is closed https://github.com/kubernetes-sigs/sig-windows-tools/pull/239.
Docs: https://github.com/kubernetes-sigs/sig-windows-tools/blob/master/guides/guide-for-adding-windows-node.md

**Comment by rabejens** [comment]
I managed to get a worker node with Kubernetes 1.25.6 running with Windows Server 2022 and Calico networking. Here is what I did:

1. Using [calicoctl](https://github.com/projectcalico/calico/releases), get IP pool:
    ```bash
    calicoctl get ippool -o wide
    ```
2. Get DNS address
    ```bash
    kubectl -n kube-system get svc/coredns
    ```
3. Install ContainerD and prepare the nodes as per Tigera's guide:
    ```powershell
    Invoke-WebRequest https://docs.tigera.io/calico/3.25/scripts/Install-Containerd.ps1 -OutFile c:\Install-Containerd.ps1
    c:\Install-Containerd.ps1 -ContainerDVersion 1.7.0 -CNIConfigPath "c:/etc/cni/net.d" -CNIBinPath "c:/opt/cni/bin"
    # Reboot and do again if asked so
    Invoke-WebRequest https://docs.tigera.io/calico/3.25/scripts/PrepareNode.ps1 -OutFile c:\PrepareNode.ps1
    c:\PrepareNode.ps1 -KubernetesVersion v1.25.6 -ContainerRuntime ContainerD
    ```
4. Symlink `C:\etc\kubernetes\ssl` because the `ca.crt` is put in `C:\etc\kubernetes\pki`
    From elevated cmd (not powershell):
    ```cmd
    mklink /d c:\etc\kubernetes\ssl c:\etc\kubernetes\pki
    ```
5. Join the cluster
    ```powershell
    c:\k\kubeadm.exe join IP-OF-CONTROL-PLANE:PORT-OF-CONTROL-PLANE --token XXXXX... --discovery-token-ca-cert-hash sha256:XXXXX... --cri-socket "npipe:////./pipe/containerd-containerd"
    ```
6. (recommended) Taint the node so only a node toleration with `kubernetes.io/os=windows` will schedule pods (you can use `nodeSelector` but without the taint, other deployments, statefulsets, daemonsets etc. will try to sprawl to the Windows nodes which most possibly won't work)
    ```powershell
    kubectl taint nodes name-of-windows-node kubernetes.io/os=windows:NoSchedule
    ```
7. Get the manifest from Tigera:
    ```yaml
    curl https://raw.githubusercontent.com/projectcalico/calico/v3.25.1/manifests/calico-windows-vxlan.yaml -o calico-windows.yaml
    ```
8. Adjust the `ConfigMap` as in the quickstart guide (especially `KUBERNETES_SERVICE_HOST`, `KUBERNETES_SERVICE_PORT`, `K8S_SERVICE_CIDR`, `DNS_NAME_SERVERS`)
9. In the `DaemonSet`, for the `initContainers` set `workingDir` to `C:\hpc`
10. In the `DaemonSet`, for all `containers`, set `workingDir` to `C:\CalicoWindows`
11. Adjust the namespace to deploy to, my Calico was deployed to `kube-system` instead of `calico-system`
12. Apply the modified `calico-windows.yaml`
13. In the Calico namespace, watch the `calico-node-windows-.....` pod start
14. After some minutes, the node should be `Ready` but the `kube-proxy` is still missing
15. Download the [kube-proxy.yml](https://raw.githubusercontent.com/kubernetes-sigs/sig-windows-tools/master/hostprocess/calico/kube-proxy/kube-proxy.yml)
16. Adjust `KUBE_PROXY_VERSION` to your Kubernetes version, in my case, it is `1.25.6` so the `image` says something like: `sigwindowstools/kube-proxy:v1.25.6-calico-hostprocess`
17. Apply the `kube-proxy`

You can then test with a basic manifest like:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
  namespace: default
  labels:
    app: helloworld
spec:
  replicas: 1
  template:
    metadata:
      name: helloworld
      labels:
        app: helloworld
    spec:
      tolerations:
        - key: kubernetes.io/os
          operator: Equal
          value: windows
          effect: NoSchedule
      nodeSelector:
        "kubernetes.io/os": windows
        # Set below to test newly-added nodes
        # kubernetes.io/hostname: winworker02
      containers:
      - name: helloworld
        image: mcr.microsoft.com/dotnet/framework/samples:aspnetapp
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
        ports:
          - containerPort: 80
  selector:
    matchLabels:
      app: helloworld
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld
  namespace: default
  labels:
    app: helloworld
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: helloworld
```

There is still an issue that after the first pull of an image the container might get stuck in `ContainerCreating` state, if that happens, `rollout restart` the deployment one or more times.
